name: KRS Watcher (test)

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --no-audit --no-fund

      # Opcjonalnie: usuń state.json, żeby wszystkie spółki były "nowe"
      # - name: Reset state
      #   run: rm -f src/state.json

      - name: Run watcher (force-send)
        run: node src/krsWatcher.mjs --force-send
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
